### ISSUE TITLE
Define conventions for logging

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-retired/cluster-api-provider-docker#224]
/kind feature

**Describe the solution you'd like**
as per [comment](https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/210#discussion_r316740803)

> I've been using skewer-style (css-style) for the logging keys. We should pick a style and stick with it. Do you mind changing this to skewer-case for consistency and then opening an issue so we can evaluate what people want, probably at the CAPI meeting?

also relevant [comment](https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/210#discussion_r316732905) and [reply](https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/210#discussion_r316769998)
> for values i've been using skewer-style (css-style) variables, so this should bar `docker-machine unless you think we should standardize on camel case?
> I think ideally we should stick with the proper type naming to avoid confusion, so I would suggest DockerMachine. That way it is clear that we are referencing a resource of type DockerMachine rather than something else.

I would also add that some recommendations about which logger to choose and usage of log levels could be really useful...

**Comment by detiber** [comment]
As I mentioned in the PR comments, I believe we should standardize to match the type naming to avoid user confusion. Anywhere they see DockerMachine, Cluster, etc it is clear that we are talking about a resource of that type rather than one of the many other overloaded uses of the words.

**Comment by randomvariable** [comment]
Was the consensus on this to follow the object capitalization?

**Comment by chuckha** [comment]
I'm not sure there was consensus. But now would be a good time for an update:

From my perspective, skewer style looks the best, but if CAPI and CAPA have followed the object capitalization then let's do that.

The thing that's important to me is to log errors at the Reconciler level and not have too many Info logs. If we need debugging we can use `.V(1)` levels. I'm using https://github.com/kubernetes-sigs/controller-runtime/blob/master/TMP-LOGGING.md as my guide line.

**Comment by chuckha** [comment]
In my ideal world we only use `.Info`, `.V(1).Info` and `.Error` methods on the logger and nothing else.

**Comment by randomvariable** [comment]
Thanks for the update. I think we should go for the object capitalization. Brief look through k/k shows all logs follow object capitalization *except* for pod, where it is inconsistently cased through the repository.

**Comment by chuckha** [comment]
sounds great to me, thank you for poking through k/k

**Comment by randomvariable** [comment]
On the log levels front, k/k has the following conventions (found here https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md, and linked from docs.k8s.io):

The following conventions for the klog levels to use.
[klog](http://godoc.org/github.com/kubernetes/klog) is globally preferred to
[log](http://golang.org/pkg/log/) for better runtime control.

* klog.Errorf() - Always an error

* klog.Warningf() - Something unexpected, but probably not an error

* klog.Infof() has multiple levels:
  * klog.V(0) - Generally useful for this to ALWAYS be visible to an operator
    * Programmer errors
    * Logging extra info about a panic
    * CLI argument handling
  * klog.V(1) - A reasonable default log level if you don't want verbosity.
    * Information about config (listening on X, watching Y)
    * Errors that repeat frequently that relate to conditions that can be corrected (pod detected as unhealthy)
  * klog.V(2) - Useful steady state information about the service and important log messages that may correlate to significant changes in the system.  This is the recommended default log level for most systems.
    * Logging HTTP requests and their exit code
    * System state changing (killing pod)
    * Controller state change events (starting pods)
    * Scheduler log messages
  * klog.V(3) - Extended information about changes
    * More info about system state changes
  * klog.V(4) - Debug level verbosity
    * Logging in particularly thorny parts of code where you may want to come back later and check it
  * klog.V(5) - Trace level verbosity
    * Context to understand the steps leading up to errors and warnings
    * More information for troubleshooting reported issues

As per the comments, the practical default level is V(2). Developers and QE
environments may wish to run at V(3) or V(4). If you wish to change the log
level, you can pass in `-v=X` where X is the desired maximum level to log.

**Comment by chuckha** [comment]
k/k logging is not the convention in controller-runtime based projects. The reason I have this issue opened is that the provider logs are generally not useful (overly verbose) and I want to see if we can make them more useful. As a developer, I know what I want to see when someone comes to us with a bug. I want a stack trace.

The controller-runtime sets a logging convention of favoring logging as a dependency (no global klog calls) and recommends using v(0) for everything and v(1) for debugging. It recommends only Info and Error calls to the logging interface and never anything other than v(1).

I think errors should only be logged at the reconciler level with a stack trace. We should not tell the user there was an error when that case is actually expected. We should handle the errors properly.

I will propose that we always log errors at the top level, the majority of logs move to .v(1), except for the functions that are only executed on the first successful reconciliation loop. No (or very few) logs should execute in every loop of the reconciler.

**Comment by mrbobbytables** [comment]
Project is to be archived - closing issue.
ref: https://github.com/kubernetes/org/issues/2888
